Add retry when start emulator failed

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -75,20 +75,17 @@ runs:
         mvn install -DskipTests > /dev/null 2>&1
       shell: bash
 
-    - name: Run Appium tests with Maven
+    - name: Run Appium tests with Maven (Retry if ADB Offline)
       run: |
-        - name: Run Appium tests with Maven (Retry if ADB Offline)
-  run: |
-    for i in {1..3}; do
-      eval "${{ inputs.scripts }}" && break || {
-        echo "⚠️ Tests failed (attempt $i), restarting ADB..."
-        $ANDROID_HOME/platform-tools/adb kill-server
-        $ANDROID_HOME/platform-tools/adb start-server
-        sleep 10
-        $ANDROID_HOME/platform-tools/adb devices
-      }
-    done
-  shell: bash
+        for i in {1..3}; do
+          eval "${{ inputs.scripts }}" && break || {
+            echo "⚠️ Tests failed (attempt $i), restarting ADB..."
+            $ANDROID_HOME/platform-tools/adb kill-server
+            $ANDROID_HOME/platform-tools/adb start-server
+            sleep 10
+            $ANDROID_HOME/platform-tools/adb devices
+          }
+        done
       shell: bash
 
     - name: Upload Test Report
