Add retry condition

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -75,17 +75,19 @@ runs:
         mvn install -DskipTests > /dev/null 2>&1
       shell: bash
 
-    - name: Run Appium tests with Maven (Retry if ADB Offline)
+    - name: Run Appium tests with ADB Restart on Failure
       run: |
-        for i in {1..3}; do
-          eval "${{ inputs.scripts }}" && break || {
-            echo "⚠️ Tests failed (attempt $i), restarting ADB..."
+        output=$(eval "${{ inputs.scripts }}" 2>&1) || {
+          echo "$output" | tee appium.log
+          if echo "$output" | grep -q "SessionNotCreated Could not start a new session."; then
+            echo "⚠️ Detected 'SessionNotCreated' error, restarting ADB..."
             $ANDROID_HOME/platform-tools/adb kill-server
             $ANDROID_HOME/platform-tools/adb start-server
             sleep 10
             $ANDROID_HOME/platform-tools/adb devices
-          }
-        done
+            eval "${{ inputs.scripts }}"
+          fi
+        }
       shell: bash
 
     - name: Upload Test Report
